# Generated by Django 4.1.2 on 2022-11-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_c_off_bidding_bid_price_remove_bidding_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='c_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bidprices', to='auctions.bidding'),
        ),
    ]
